//! GPU/backend cross-check command.
//!
//! Corresponds to `MainCmds::testgpuerror` in `cpp/command/gputest.cpp`.
//!
//! The C++ implementation loads a neural net twice (once with the current
//! backend's default precision, once forced to FP32) and runs
//! `Tests::runBackendErrorTest` to compare policy/value outputs across batch
//! sizes and precisions. The Rust port does not yet implement the underlying
//! backend error test, so this command parses the expected flags and reports
//! that the test is not available.

#![allow(dead_code)]

use std::io::Write;

use clap::Parser;

use kata_core::global::StringError;

use crate::cli::CommonArgs;

/// CLI arguments for the `testgpuerror` subcommand.
#[derive(Parser, Debug, Clone)]
struct GpuTestArgs {
    #[command(flatten)]
    common: CommonArgs,

    /// Board size dataset to test on.
    #[arg(long = "boardsize", value_name = "SIZE", default_value = "19")]
    board_size: String,

    /// Run a faster, shorter test.
    #[arg(long = "quick")]
    quick: bool,

    /// Reference file generated by the Eigen backend for cross-backend checks.
    #[arg(long = "reference-file", value_name = "FILE")]
    reference_file: Option<String>,
}

/// Public CLI entry point.
pub fn testgpuerror(args: &[String]) -> i32 {
    let mut out = std::io::stdout();
    match testgpuerror_impl(args, &mut out) {
        Ok(()) => 0,
        Err(e) => {
            eprintln!("Error: {}", e);
            1
        }
    }
}

fn testgpuerror_impl(args: &[String], out: &mut dyn Write) -> Result<(), StringError> {
    let parsed = GpuTestArgs::try_parse_from(
        std::iter::once(&"testgpuerror".to_string()).chain(args.iter()),
    )
    .map_err(|e| StringError::new(format!("Argument error: {}", e)))?;

    match parsed.board_size.as_str() {
        "9" | "13" | "19" | "10x14" | "rectangle" => {}
        other => {
            return Err(StringError::new(format!(
                "Board size dataset to test: invalid value {}",
                other
            )));
        }
    }

    let model_file = parsed
        .common
        .get_model_file()
        .unwrap_or_else(|_| String::from("(default not found)"));

    writeln!(
        out,
        "Testing average errors between different GPU configurations..."
    )
    .map_err(|e| StringError::new(e.to_string()))?;
    writeln!(out, "Model: {}", model_file).map_err(|e| StringError::new(e.to_string()))?;
    writeln!(out, "Board size dataset: {}", parsed.board_size)
        .map_err(|e| StringError::new(e.to_string()))?;
    if parsed.quick {
        writeln!(out, "Quick test requested").map_err(|e| StringError::new(e.to_string()))?;
    }
    if let Some(reference) = &parsed.reference_file {
        writeln!(out, "Reference file: {}", reference)
            .map_err(|e| StringError::new(e.to_string()))?;
    }
    writeln!(
        out,
        "Cross-backend GPU error testing is not yet implemented in the Rust port."
    )
    .map_err(|e| StringError::new(e.to_string()))?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_testgpuerror_parses_args() {
        let args = GpuTestArgs::parse_from([
            "testgpuerror",
            "--model",
            "model.bin.gz",
            "--boardsize",
            "13",
            "--quick",
            "--reference-file",
            "ref.txt",
        ]);
        assert_eq!(args.common.model, Some("model.bin.gz".to_string()));
        assert_eq!(args.board_size, "13");
        assert!(args.quick);
        assert_eq!(args.reference_file, Some("ref.txt".to_string()));
    }

    #[test]
    fn test_testgpuerror_rejects_invalid_board_size() {
        let result = testgpuerror_impl(
            &["--model", "/dev/null", "--boardsize", "5"]
                .iter()
                .map(|s| s.to_string())
                .collect::<Vec<_>>(),
            &mut Vec::new(),
        );
        assert!(result.is_err());
    }

    #[test]
    fn test_testgpuerror_runs_and_reports_not_implemented() {
        let mut out = Vec::new();
        let result = testgpuerror_impl(
            &["--model", "/dev/null", "--boardsize", "19", "--quick"]
                .iter()
                .map(|s| s.to_string())
                .collect::<Vec<_>>(),
            &mut out,
        );
        assert!(result.is_ok());
        let output = String::from_utf8_lossy(&out);
        assert!(output.contains("GPU error testing"));
    }
}
