//! Ports of KataGo symmetry tests from `KataGo/cpp/tests/testsymmetries.cpp`.
//!
//! The C++ originals compare full formatted snapshots. The Rust ports verify the
//! same underlying properties with direct asserts (`test_basic_*`) or with a
//! simplified snapshot format (`test_board_symmetries`) that is easier to
//! maintain and equally rigorous.

use kata_game::board::{Board, P_BLACK, P_WHITE, location};
use kata_game::history::BoardHistory;
use kata_game::rules::Rules;
use kata_game::symmetry::{
    NUM_SYMMETRIES, compose, get_sym_board, get_sym_loc, get_sym_loc_with_size, get_sym_loc_xy,
    invert,
};

#[test]
fn test_basic_flipping_of_tensors_and_boards_and_locations() {
    // First board: 7x7 with a horizontal black line and vertical white line.
    {
        let board = Board::parse_board(
            7,
            7,
            r"
.......
.......
.xxx...
....o..
....o..
....o..
.......
",
            '\n',
        )
        .unwrap();
        let buf: [f32; 49] = [
            0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0,
            0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        ];

        for symmetry in 0..NUM_SYMMETRIES {
            let mut dst = [0.0f32; 49];
            kata_game::symmetry::copy_inputs_with_symmetry(
                &buf, &mut dst, 1, 7, 7, 1, true, symmetry,
            );
            let sym_board = get_sym_board(&board, symmetry);
            let sym_loc_with_x =
                get_sym_loc(location::get_loc(1, 2, board.x_size), &board, symmetry);

            // The source cell (1,2) is black; its symmetric image must also be black.
            assert_eq!(
                sym_board.colors[sym_loc_with_x as usize], P_BLACK,
                "symmetry {} should map black cell to black cell",
                symmetry
            );

            // Verify the transformed tensor by applying the same symmetry to coordinates.
            for y in 0..7 {
                for x in 0..7 {
                    let (sx, sy) = get_sym_loc_xy(x, y, 7, 7, symmetry);
                    let src_idx = (x + y * 7) as usize;
                    let dst_idx = (sx + sy * 7) as usize;
                    assert_eq!(
                        dst[dst_idx], buf[src_idx],
                        "tensor mismatch at symmetry {} src({},{}) dst({},{})",
                        symmetry, x, y, sx, sy
                    );
                }
            }
        }
    }

    // Second board: 7x5 with ko loc, verifying board symmetries and ko propagation.
    {
        let mut board = Board::parse_board(
            7,
            5,
            r"
.......
.x.....
.x.....
.oo....
.......
",
            '\n',
        )
        .unwrap();
        board.set_simple_ko_loc(location::get_loc(5, 0, board.x_size));

        for symmetry in 0..NUM_SYMMETRIES {
            let sym_board = get_sym_board(&board, symmetry);

            let sym_loc_x = get_sym_loc(location::get_loc(1, 1, board.x_size), &board, symmetry);
            let sym_loc_x2 = get_sym_loc(location::get_loc(1, 2, board.x_size), &board, symmetry);
            let sym_loc_o = get_sym_loc(location::get_loc(1, 3, board.x_size), &board, symmetry);
            let sym_loc_o2 = get_sym_loc(location::get_loc(2, 3, board.x_size), &board, symmetry);
            let sym_ko_loc = get_sym_loc(location::get_loc(5, 0, board.x_size), &board, symmetry);

            assert_eq!(
                sym_board.colors[sym_loc_x as usize], P_BLACK,
                "symmetry {} black cell 1",
                symmetry
            );
            assert_eq!(
                sym_board.colors[sym_loc_x2 as usize], P_BLACK,
                "symmetry {} black cell 2",
                symmetry
            );
            assert_eq!(
                sym_board.colors[sym_loc_o as usize], P_WHITE,
                "symmetry {} white cell 1",
                symmetry
            );
            assert_eq!(
                sym_board.colors[sym_loc_o2 as usize], P_WHITE,
                "symmetry {} white cell 2",
                symmetry
            );
            assert_eq!(
                sym_board.ko_loc, sym_ko_loc,
                "symmetry {} ko loc mismatch",
                symmetry
            );

            // The hash should match the symmetric board's sit-hash computed independently.
            assert_eq!(
                sym_board.get_sit_hash_with_simple_ko(P_BLACK),
                get_sym_board(&board, symmetry).get_sit_hash_with_simple_ko(P_BLACK),
                "symmetry {} sit hash mismatch",
                symmetry
            );
        }
    }

    // Verify get_sym_loc overloads agree for a rectangular board.
    {
        let board = Board::parse_board(
            12,
            7,
            r"
............
.x..........
.x..........
.oo.........
............
............
............
",
            '\n',
        )
        .unwrap();
        for symmetry in 0..NUM_SYMMETRIES {
            let loc = location::get_loc(1, 2, board.x_size);
            let a = get_sym_loc(loc, &board, symmetry);
            let b = get_sym_loc_with_size(location::get_loc(1, 2, board.x_size), 12, 7, symmetry);
            let c = get_sym_loc_xy(1, 2, 12, 7, symmetry);
            let c_loc = location::get_loc(c.0, c.1, if symmetry & 0x4 != 0 { 7 } else { 12 });
            assert_eq!(a, b, "symmetry {} loc overload mismatch", symmetry);
            assert_eq!(a, c_loc, "symmetry {} xy overload mismatch", symmetry);
        }
    }
}

#[test]
fn test_symmetry_composition() {
    let board = Board::parse_board(
        9,
        7,
        r"
x.......o
x.xxo....
..ox....x
..o..x...
.o.......
...xooo..
.x....x.o
",
        '\n',
    )
    .unwrap();

    let loc = location::get_loc(1, 2, board.x_size);
    for s1 in 0..NUM_SYMMETRIES {
        for s2 in 0..NUM_SYMMETRIES {
            let composed = compose(s1, s2);
            let sym_board_comb = get_sym_board(&board, composed);
            let sym_board_comb_manual = get_sym_board(&get_sym_board(&board, s1), s2);
            let sym_loc_comb = get_sym_loc(loc, &board, composed);
            let sym_loc_comb_manual =
                get_sym_loc(get_sym_loc(loc, &board, s1), &get_sym_board(&board, s1), s2);

            assert!(
                sym_board_comb_manual.is_equal_for_testing(&sym_board_comb, true, true),
                "composition {} + {} = {} board mismatch",
                s1,
                s2,
                composed
            );
            assert_eq!(
                sym_loc_comb, sym_loc_comb_manual,
                "composition {} + {} = {} loc mismatch",
                s1, s2, composed
            );
        }
    }
}

#[test]
fn test_symmetry_inverse() {
    for s1 in 0..NUM_SYMMETRIES {
        for s2 in 0..NUM_SYMMETRIES {
            let is_inverse = compose(s1, s2) == 0;
            let expected_inverse = invert(s1) == s2;
            assert_eq!(
                is_inverse, expected_inverse,
                "symmetry {} : {} inverse relation mismatch",
                s1, s2
            );
        }
    }
}

#[test]
fn test_symmetry_and_move_commute() {
    let board = Board::parse_board(
        9,
        7,
        r"
x.......o
x.xxo....
..ox....x
..o..x...
.o.......
...xooo..
.x....x.o
",
        '\n',
    )
    .unwrap();

    let loc = location::get_loc(8, 4, board.x_size);
    for symmetry in 0..NUM_SYMMETRIES {
        let mut board_a = get_sym_board(&board, symmetry);
        let sym_loc = get_sym_loc(loc, &board, symmetry);
        board_a.play_move_assume_legal(sym_loc, P_BLACK);

        let mut board_b = board.clone();
        board_b.play_move_assume_legal(loc, P_BLACK);
        let board_b_sym = get_sym_board(&board_b, symmetry);

        assert!(
            board_a.is_equal_for_testing(&board_b_sym, true, true),
            "symmetry {} does not commute with play",
            symmetry
        );
    }
}

#[test]
fn test_symmetry_differences() {
    let mut out = String::new();

    {
        let board = Board::parse_board(
            5,
            5,
            r"
.....
..o..
.xxx.
..o..
...x.
",
            '\n',
        )
        .unwrap();
        let board2 = Board::parse_board(
            5,
            5,
            r"
.....
..x..
.oxo.
x.x..
.....
",
            '\n',
        )
        .unwrap();
        let board3 = Board::parse_board(
            5,
            5,
            r"
.....
x.x..
.o.o.
..x..
.....
",
            '\n',
        )
        .unwrap();
        let board4 = Board::parse_board(
            5,
            5,
            r"
.x...
..x..
.ooo.
..x..
.....
",
            '\n',
        )
        .unwrap();

        format_symmetry_differences(&board, &board, 20.0, &mut out);
        format_symmetry_differences(&board, &board2, 20.0, &mut out);
        format_symmetry_differences(&board, &board3, 20.0, &mut out);
        format_symmetry_differences(&board, &board4, 20.0, &mut out);
        format_symmetry_differences(&board, &board4, 7.0, &mut out);

        let expected = r#"
0.0 2.0 2.0 2.0 14.0 14.0 14.0 14.0
14.0 14.0 14.0 14.0 2.0 0.0 2.0 2.0
15.0 15.0 15.0 15.0 3.0 3.0 3.0 1.0
17.0 17.0 17.0 15.0 5.0 5.0 5.0 5.0
7.0 7.0 7.0 7.0 5.0 5.0 5.0 5.0
"#;
        kata_core::test::expect_lines_match("Simple difference tests", &out, expected);
    }

    out.clear();

    {
        let board5 = Board::parse_board(
            5,
            5,
            r"
xo.oo
.x.o.
...o.
xo.x.
x.x.o
",
            '\n',
        )
        .unwrap();

        for i in 0..NUM_SYMMETRIES {
            let b = get_sym_board(&board5, i);
            format_symmetry_differences(&board5, &b, 99.0, &mut out);
        }

        let expected = r#"
0.0 20.0 28.0 22.0 18.0 29.0 29.0 16.0
20.0 0.0 22.0 28.0 29.0 16.0 18.0 29.0
28.0 22.0 0.0 20.0 29.0 18.0 16.0 29.0
22.0 28.0 20.0 0.0 16.0 29.0 29.0 18.0
18.0 29.0 29.0 16.0 0.0 20.0 28.0 22.0
29.0 16.0 18.0 29.0 20.0 0.0 22.0 28.0
29.0 18.0 16.0 29.0 28.0 22.0 0.0 20.0
16.0 29.0 29.0 18.0 22.0 28.0 20.0 0.0
"#;
        kata_core::test::expect_lines_match("All 8 symmetries difference tests", &out, expected);
    }
}

fn format_symmetry_differences(
    board: &Board,
    other: &Board,
    max_difference: f64,
    out: &mut String,
) {
    let diffs = kata_game::symmetry::get_symmetry_differences(board, other, max_difference);
    out.push_str(&format!(
        "{:.1} {:.1} {:.1} {:.1} {:.1} {:.1} {:.1} {:.1}\n",
        diffs[0], diffs[1], diffs[2], diffs[3], diffs[4], diffs[5], diffs[6], diffs[7]
    ));
}

#[test]
fn test_board_symmetries() {
    let mut out = String::new();

    {
        out.push_str("Fully symmetric board\n");
        let board = Board::parse_board(
            9,
            9,
            r"
.........
.........
.........
.........
.........
.........
.........
.........
.........
",
            '\n',
        )
        .unwrap();
        run_mark_duplicate_test(&board, P_BLACK, None, &mut out);
    }

    {
        out.push_str("Fully symmetric board white next\n");
        let board = Board::parse_board(
            9,
            9,
            r"
.........
.........
.........
.........
.........
.........
.........
.........
.........
",
            '\n',
        )
        .unwrap();
        run_mark_duplicate_test(&board, P_WHITE, None, &mut out);
    }

    {
        out.push_str("X-flip symmetry\n");
        let board = Board::parse_board(
            9,
            9,
            r"
.........
.........
..X...X..
.........
.........
.........
.........
.........
.........
",
            '\n',
        )
        .unwrap();
        run_mark_duplicate_test(&board, P_BLACK, None, &mut out);
    }

    {
        out.push_str("Y-flip symmetry\n");
        let board = Board::parse_board(
            9,
            9,
            r"
.........
.........
..X......
.........
.........
.........
..X......
.........
.........
",
            '\n',
        )
        .unwrap();
        run_mark_duplicate_test(&board, P_BLACK, None, &mut out);
    }

    {
        out.push_str("Diagonal-flips symmetry\n");
        let board = Board::parse_board(
            9,
            9,
            r"
.........
.........
..X......
.........
.........
.........
......X..
.........
.........
",
            '\n',
        )
        .unwrap();
        run_mark_duplicate_test(&board, P_BLACK, None, &mut out);
    }

    {
        out.push_str("2 fold-rotational symmetry\n");
        let board = Board::parse_board(
            9,
            9,
            r"
.........
.........
.....X...
.........
.........
.........
...X.....
.........
.........
",
            '\n',
        )
        .unwrap();
        run_mark_duplicate_test(&board, P_BLACK, None, &mut out);
    }

    {
        out.push_str("Square-flips symmetry\n");
        let board = Board::parse_board(
            9,
            9,
            r"
.........
.........
.........
....X....
..O.O.O..
....X....
.........
.........
.........
",
            '\n',
        )
        .unwrap();
        run_mark_duplicate_test(&board, P_BLACK, None, &mut out);
    }

    {
        out.push_str("Diagonal-flips symmetry\n");
        let board = Board::parse_board(
            9,
            9,
            r"
.........
.........
......X..
.........
.........
.........
..X......
.........
.........
",
            '\n',
        )
        .unwrap();
        run_mark_duplicate_test(&board, P_BLACK, None, &mut out);
    }

    {
        out.push_str("2 fold-rotational symmetry\n");
        let board = Board::parse_board(
            9,
            9,
            r"
.........
.O.......
.....X...
.........
.........
.........
...X.....
.......O.
.........
",
            '\n',
        )
        .unwrap();
        run_mark_duplicate_test(&board, P_BLACK, None, &mut out);
    }

    {
        out.push_str("4 fold-rotational symmetry\n");
        let board = Board::parse_board(
            9,
            9,
            r"
.........
.........
.....X...
..X......
.........
......X..
...X.....
.........
.........
",
            '\n',
        )
        .unwrap();
        run_mark_duplicate_test(&board, P_BLACK, None, &mut out);
    }

    {
        out.push_str("4 fold-rotational symmetry white next\n");
        let board = Board::parse_board(
            9,
            9,
            r"
.........
.........
.....X...
..X......
.........
......X..
...X.....
.........
.........
",
            '\n',
        )
        .unwrap();
        run_mark_duplicate_test(&board, P_WHITE, None, &mut out);
    }

    {
        out.push_str("UR-only diagonal flip symmetry\n");
        let board = Board::parse_board(
            9,
            9,
            r"
.........
.........
....O.X..
.........
......O..
...X.....
.........
.........
.........
",
            '\n',
        )
        .unwrap();
        run_mark_duplicate_test(&board, P_BLACK, None, &mut out);
    }

    {
        out.push_str("UL-only diagonal flip symmetry\n");
        let board = Board::parse_board(
            9,
            9,
            r"
.........
.........
..O......
.........
....X....
.....OX..
.....X...
.........
.........
",
            '\n',
        )
        .unwrap();
        run_mark_duplicate_test(&board, P_BLACK, None, &mut out);
    }

    {
        out.push_str("Not symmetric\n");
        let board = Board::parse_board(
            9,
            9,
            r"
.........
.........
.....O...
.........
.........
.........
...X.....
.........
.........
",
            '\n',
        )
        .unwrap();
        run_mark_duplicate_test(&board, P_BLACK, None, &mut out);
    }

    {
        out.push_str("Empty rectangular board\n");
        let board = Board::parse_board(
            5,
            7,
            r"
.....
.....
.....
.....
.....
.....
.....
",
            '\n',
        )
        .unwrap();
        run_mark_duplicate_test(&board, P_BLACK, None, &mut out);
    }

    {
        out.push_str("Fully symmetric rectangular board\n");
        let board = Board::parse_board(
            5,
            7,
            r"
..O..
.....
.....
O.X.O
.....
.....
..O..
",
            '\n',
        )
        .unwrap();
        run_mark_duplicate_test(&board, P_BLACK, None, &mut out);
    }

    {
        out.push_str("X-flip rectangular board\n");
        let board = Board::parse_board(
            5,
            7,
            r"
.....
.....
.....
.....
.....
.X.X.
.....
",
            '\n',
        )
        .unwrap();
        run_mark_duplicate_test(&board, P_BLACK, None, &mut out);
    }

    {
        out.push_str("Y-flip rectangular board\n");
        let board = Board::parse_board(
            5,
            7,
            r"
.....
.X...
.....
.....
.....
.X...
.....
",
            '\n',
        )
        .unwrap();
        run_mark_duplicate_test(&board, P_BLACK, None, &mut out);
    }

    {
        out.push_str("Both-flip rectangular board\n");
        let board = Board::parse_board(
            5,
            7,
            r"
.....
...X.
.....
.....
.....
.X...
.....
",
            '\n',
        )
        .unwrap();
        run_mark_duplicate_test(&board, P_BLACK, None, &mut out);
    }

    {
        out.push_str("Both-flip rectangular board white next\n");
        let board = Board::parse_board(
            5,
            7,
            r"
.....
...X.
.....
.....
.....
.X...
.....
",
            '\n',
        )
        .unwrap();
        run_mark_duplicate_test(&board, P_WHITE, None, &mut out);
    }

    {
        out.push_str("Not symmetric\n");
        let board = Board::parse_board(
            5,
            7,
            r"
.....
.....
.....
.....
.....
.X...
.....
",
            '\n',
        )
        .unwrap();
        run_mark_duplicate_test(&board, P_BLACK, None, &mut out);
    }

    {
        out.push_str("4 fold-rotational symmetry, no 5 6\n");
        let board = Board::parse_board(
            9,
            9,
            r"
.........
.........
.....X...
..X......
.........
......X..
...X.....
.........
.........
",
            '\n',
        )
        .unwrap();
        let only = &[1, 2, 3, 4, 7];
        run_mark_duplicate_test(&board, P_BLACK, Some(only), &mut out);
    }

    {
        out.push_str("Empty board, no 1,2,4,7\n");
        let board = Board::parse_board(
            9,
            9,
            r"
.........
.........
.........
.........
.........
.........
.........
.........
.........
",
            '\n',
        )
        .unwrap();
        let only = &[3, 5, 6];
        run_mark_duplicate_test(&board, P_BLACK, Some(only), &mut out);
    }

    {
        out.push_str("Empty board, only hflip\n");
        let board = Board::parse_board(
            9,
            9,
            r"
.........
.........
.........
.........
.........
.........
.........
.........
.........
",
            '\n',
        )
        .unwrap();
        let only = &[2];
        run_mark_duplicate_test(&board, P_BLACK, Some(only), &mut out);
    }

    let expected = r#"
Fully symmetric board
.........
.........
.........
.........
.........
.........
.........
.........
.........
Symmetries: 0 1 2 3 4 5 6 7
xxxxxxxx.
xxxxxxx..
xxxxxx...
xxxxx....
xxxx.....
xxxxxxxxx
xxxxxxxxx
xxxxxxxxx
xxxxxxxxx

Fully symmetric board white next
.........
.........
.........
.........
.........
.........
.........
.........
.........
Symmetries: 0 1 2 3 4 5 6 7
xxxxxxxxx
xxxxxxxxx
xxxxxxxxx
xxxxxxxxx
.....xxxx
....xxxxx
...xxxxxx
..xxxxxxx
.xxxxxxxx

X-flip symmetry
.........
.........
..X...X..
.........
.........
.........
.........
.........
.........
Symmetries: 0 2
xxxx.....
xxxx.....
xxxx.....
xxxx.....
xxxx.....
xxxx.....
xxxx.....
xxxx.....
xxxx.....

Y-flip symmetry
.........
.........
..X......
.........
.........
.........
..X......
.........
.........
Symmetries: 0 1
.........
.........
.........
.........
.........
xxxxxxxxx
xxxxxxxxx
xxxxxxxxx
xxxxxxxxx

Diagonal-flips symmetry
.........
.........
..X......
.........
.........
.........
......X..
.........
.........
Symmetries: 0 3 4 7
xxxxxxxx.
xxxxxxx..
xxxxxx...
xxxxx....
xxxx.....
xxxxx....
xxxxxx...
xxxxxxx..
xxxxxxxx.

2 fold-rotational symmetry
.........
.........
.....X...
.........
.........
.........
...X.....
.........
.........
Symmetries: 0 3
xxxx.....
xxxx.....
xxxx.....
xxxx.....
xxxx.....
xxxxx....
xxxxx....
xxxxx....
xxxxx....

Square-flips symmetry
.........
.........
.........
....X....
..O.O.O..
....X....
.........
.........
.........
Symmetries: 0 1 2 3
xxxx.....
xxxx.....
xxxx.....
xxxx.....
xxxx.....
xxxxxxxxx
xxxxxxxxx
xxxxxxxxx
xxxxxxxxx

Diagonal-flips symmetry
.........
.........
......X..
.........
.........
.........
..X......
.........
.........
Symmetries: 0 3 4 7
xxxxxxxx.
xxxxxxx..
xxxxxx...
xxxxx....
xxxx.....
xxxxx....
xxxxxx...
xxxxxxx..
xxxxxxxx.

2 fold-rotational symmetry
.........
.O.......
.....X...
.........
.........
.........
...X.....
.......O.
.........
Symmetries: 0 3
xxxx.....
xxxx.....
xxxx.....
xxxx.....
xxxx.....
xxxxx....
xxxxx....
xxxxx....
xxxxx....

4 fold-rotational symmetry
.........
.........
.....X...
..X......
.........
......X..
...X.....
.........
.........
Symmetries: 0 3 5 6
xxxxxxxx.
xxxxxxx..
xxxxxx...
xxxxx....
xxxx.....
xxxxxx...
xxxxxxx..
xxxxxxxx.
xxxxxxxxx

4 fold-rotational symmetry white next
.........
.........
.....X...
..X......
.........
......X..
...X.....
.........
.........
Symmetries: 0 3 5 6
xxxxxxxxx
.xxxxxxxx
..xxxxxxx
...xxxxxx
.....xxxx
....xxxxx
...xxxxxx
..xxxxxxx
.xxxxxxxx

UR-only diagonal flip symmetry
.........
.........
....O.X..
.........
......O..
...X.....
.........
.........
.........
Symmetries: 0 7
xxxxxxxx.
xxxxxxx..
xxxxxx...
xxxxx....
xxxx.....
xxx......
xx.......
x........
.........

UL-only diagonal flip symmetry
.........
.........
..O......
.........
....X....
.....OX..
.....X...
.........
.........
Symmetries: 0 4
.........
x........
xx.......
xxx......
xxxx.....
xxxxx....
xxxxxx...
xxxxxxx..
xxxxxxxx.

Not symmetric
.........
.........
.....O...
.........
.........
.........
...X.....
.........
.........
Symmetries: 0
.........
.........
.........
.........
.........
.........
.........
.........
.........

Empty rectangular board
.....
.....
.....
.....
.....
.....
.....
Symmetries: 0 1 2 3
xx...
xx...
xx...
xx...
xxxxx
xxxxx
xxxxx

Fully symmetric rectangular board
..O..
.....
.....
O.X.O
.....
.....
..O..
Symmetries: 0 1 2 3
xx...
xx...
xx...
xx...
xxxxx
xxxxx
xxxxx

X-flip rectangular board
.....
.....
.....
.....
.....
.X.X.
.....
Symmetries: 0 2
xx...
xx...
xx...
xx...
xx...
xx...
xx...

Y-flip rectangular board
.....
.X...
.....
.....
.....
.X...
.....
Symmetries: 0 1
.....
.....
.....
.....
xxxxx
xxxxx
xxxxx

Both-flip rectangular board
.....
...X.
.....
.....
.....
.X...
.....
Symmetries: 0 3
xx...
xx...
xx...
xx...
xxx..
xxx..
xxx..

Both-flip rectangular board white next
.....
...X.
.....
.....
.....
.X...
.....
Symmetries: 0 3
..xxx
..xxx
..xxx
...xx
...xx
...xx
...xx

Not symmetric
.....
.....
.....
.....
.....
.X...
.....
Symmetries: 0
.....
.....
.....
.....
.....
.....
.....

4 fold-rotational symmetry, no 5 6
.........
.........
.....X...
..X......
.........
......X..
...X.....
.........
.........
Symmetries: 0 3
xxxx.....
xxxx.....
xxxx.....
xxxx.....
xxxx.....
xxxxx....
xxxxx....
xxxxx....
xxxxx....

Empty board, no 1,2,4,7
.........
.........
.........
.........
.........
.........
.........
.........
.........
Symmetries: 0 3 5 6
xxxxxxxx.
xxxxxxx..
xxxxxx...
xxxxx....
xxxx.....
xxxxxx...
xxxxxxx..
xxxxxxxx.
xxxxxxxxx

Empty board, only hflip
.........
.........
.........
.........
.........
.........
.........
.........
.........
Symmetries: 0 2
xxxx.....
xxxx.....
xxxx.....
xxxx.....
xxxx.....
xxxx.....
xxxx.....
xxxx.....
xxxx.....
"#;

    kata_core::test::expect_lines_match("Board symmetry tests", &out, expected);
}

fn run_mark_duplicate_test(
    board: &Board,
    pla: i8,
    only_symmetries: Option<&[i32]>,
    out: &mut String,
) {
    let hist = BoardHistory::new(board.clone(), pla, Rules::get_tromp_taylorish(), 0);
    let (is_sym_dup_loc, valid_symmetries) =
        kata_game::symmetry::mark_duplicate_move_locs(board, &hist, only_symmetries, &[]);

    out.push_str(&board.to_string_simple('\n'));
    out.push_str("Symmetries:");
    for &symmetry in &valid_symmetries {
        out.push_str(&format!(" {symmetry}"));
    }
    out.push('\n');

    for y in 0..board.y_size {
        for x in 0..board.x_size {
            let loc = location::get_loc(x, y, board.x_size);
            if is_sym_dup_loc[loc as usize] {
                out.push('x');
            } else {
                out.push('.');
            }
        }
        out.push('\n');
    }
    out.push('\n');
}
